### ISSUE TITLE
`get_parent()` returning `null` when attempting to call `load_shortcuts()`

### ISSUE THREAD

**Issue by stepcut** [ThemeFuse/Unyson-PageBuilder-Extension#81]
I have the latest ThemeFuse and extensions installed from github. When I try to view any page on my site, I get an Internal Server Error 500. The logs contain the following error:

```
[Tue Feb 14 20:22:33.766810 2017] [:error] [pid 26298] [client 24.14.36.86:61810] PHP Fatal error:  Uncaught Error: Call to a member function load_shortcodes() on null in /nix/store/j09s3d52chlfh9kc1grpc5ykp69vkx3p-wordpress-plugin-unyson/unyson/framework/extensions/page-builder/class-fw-extension-page-builder.php:110
Stack trace:
#0 /nix/store/qfxkb7mhw1hlxz5h9q3zwwmagqsqjx36-wordpress-4.7.2/wp-includes/class-wp-hook.php(298): FW_Extension_Page_Builder->_admin_filter_fw_post_options(Array, 'page')
#1 /nix/store/qfxkb7mhw1hlxz5h9q3zwwmagqsqjx36-wordpress-4.7.2/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /nix/store/j09s3d52chlfh9kc1grpc5ykp69vkx3p-wordpress-plugin-unyson/unyson/framework/core/components/theme.php(116): apply_filters('fw_post_options', Array, 'page')
#3 /nix/store/j09s3d52chlfh9kc1grpc5ykp69vkx3p-wordpress-plugin-unyson/unyson/framework/helpers/database.php(157): _FW_Component_Theme->get_post_options('page')
#4 /nix/store/j09s3d52chlfh9kc1grpc5ykp69vkx3p-wordpress-plugin-unyson/unyson/framework/helpers/class-fw-db-options-model.php(158): FW_Db_Options_Model_Post->get_ in /nix/store/j09s3d52chlfh9kc1grpc5ykp69vkx3p-wordpress-plugin-unyson/unyson/framework/extensions/page-builder/class-fw-extension-page-builder.php on line 110
```

Looking at the source for `PageBuilder` is not clear how the `parent` would get set in the first place.

**Comment by moldcraft** [comment]
```
unyson/framework/extensions/page-builder
```

You placed the PageBuilder extension in wrong path. It must be inside Shortcodes extension.

**Comment by stepcut** [comment]
Thanks! This solved my problem.
